#pragma once

#include <Arduino.h>

namespace WifiSetupPage {

static const char PAGE[] PROGMEM = R"HTML(<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Configurazione Wi-Fi</title><style>
:root{color-scheme:dark;--bg:#08111f;--panel:#0d1829;--line:#26384e;--text:#e8eef8;--muted:#8fa7c5;--ok:#30d99a;--warn:#f0b24a;--bad:#ff7070;--blue:#55aef6}*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#08111f,#07101c);color:var(--text);font-family:system-ui,-apple-system,Segoe UI,Arial,sans-serif}main{max-width:760px;margin:auto;padding:18px 12px}.box{border:1px solid var(--line);border-radius:13px;background:var(--panel);overflow:hidden;box-shadow:0 16px 60px #0005}.head{padding:16px 18px;border-bottom:1px solid var(--line)}h1{font-size:1.25rem;margin:0 0 4px}.sub,.hint{color:var(--muted);font-size:.78rem;line-height:1.45}.body{padding:14px 16px}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-bottom:13px}.step{border:1px solid var(--line);border-radius:9px;background:#0a1525;padding:8px;font-size:.72rem;color:var(--muted)}.step b{display:block;color:var(--text);font-size:.78rem;margin-bottom:2px}.actions{display:flex;gap:7px;flex-wrap:wrap;margin:9px 0}.btn{background:#163f63;color:#eef7ff;border:1px solid #2c5e83;border-radius:8px;padding:8px 11px;text-decoration:none;font:inherit;font-size:.8rem;font-weight:760;cursor:pointer}.btn.ok{background:#14583f;border-color:#267557}.btn:disabled{opacity:.55;cursor:wait}.status{min-height:26px;padding:6px 0;color:var(--muted);font-size:.78rem}.nets{display:grid;gap:6px;margin:4px 0 14px}.net{width:100%;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;text-align:left;border:1px solid var(--line);border-radius:9px;background:#101d30;color:var(--text);padding:9px 10px;cursor:pointer}.net:hover,.net.sel{border-color:#4b82ad;background:#13263b}.ssid{font-weight:800;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.meta{color:var(--muted);font-size:.68rem;margin-top:3px}.sig{font-weight:850;color:var(--blue);text-align:right}.current{color:var(--ok);font-size:.65rem;font-weight:800}.form{border-top:1px solid var(--line);padding-top:12px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:8px}label{display:block;color:#c8d7ea;font-size:.72rem;margin-bottom:3px}input{width:100%;padding:8px;border:1px solid #38516d;border-radius:7px;background:#e9edf2;color:#0d1722;font:inherit}.msg{margin-top:9px;padding:8px;border:1px solid var(--line);border-radius:8px;background:#0a1525;color:var(--muted);font-size:.76rem;display:none}.msg.ok{display:block;border-color:#267557;color:#a8f0d4}.msg.bad{display:block;border-color:#8c3d48;color:#ffb3b3}@media(max-width:620px){.steps,.fields{grid-template-columns:1fr}.actions .btn{flex:1}}
</style></head><body><main><div class="box"><div class="head"><h1>ESP32 Environment Sensor Hub</h1><div class="sub">Configurazione Wi-Fi iniziale · AP manutenzione 192.168.4.1</div></div><div class="body">
<div class="steps"><div class="step"><b>1 · Cerca</b>Scansiona le reti Wi-Fi visibili.</div><div class="step"><b>2 · Seleziona</b>Scegli l'SSID con il segnale migliore.</div><div class="step"><b>3 · Salva</b>Inserisci la password e riavvia.</div></div>
<div class="actions"><button id="scan" class="btn" type="button" onclick="startScan()">Cerca reti Wi-Fi</button><a class="btn" href="/config?advanced=1">Configurazione avanzata</a></div><div id="status" class="status">Ricerca reti disponibile.</div><div id="nets" class="nets"></div>
<div class="form"><div class="fields"><div><label>SSID selezionato</label><input id="ssid" maxlength="32" autocomplete="off" placeholder="Seleziona una rete dall'elenco"></div><div><label>Password Wi-Fi</label><input id="pass" type="password" maxlength="64" autocomplete="new-password" placeholder="Vuota per rete aperta"></div></div><div class="hint" style="margin-top:7px">Il setup rapido usa DHCP. IP statico, MQTT e sensori possono essere configurati successivamente dalla pagina avanzata.</div><div class="actions"><button id="save" class="btn ok" type="button" onclick="saveWifi()">Salva rete e riavvia</button></div><div id="msg" class="msg"></div></div>
</div></div></main><script>
const q=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));let selected='';
function bars(r){return r>=-55?'▮▮▮▮':r>=-67?'▮▮▮':r>=-75?'▮▮':r>=-85?'▮':'·'}
function selectNet(n,row){selected=n.ssid;q('ssid').value=n.ssid;document.querySelectorAll('.net').forEach(x=>x.classList.remove('sel'));row.classList.add('sel');q('pass').focus()}
function render(list){const box=q('nets');box.textContent='';if(!list.length){q('status').textContent='Nessuna rete visibile. Avvicinare il dispositivo al router e riprovare.';return}q('status').textContent=list.length+' reti trovate · ordinate per potenza del segnale';list.forEach(n=>{const row=document.createElement('button');row.type='button';row.className='net';const left=document.createElement('div'),name=document.createElement('div'),meta=document.createElement('div'),right=document.createElement('div');name.className='ssid';name.textContent=n.ssid;meta.className='meta';meta.textContent=(n.secure?'🔒 protetta':'🔓 aperta')+' · canale '+n.channel+(n.current?' · rete salvata':'');if(n.current){const c=document.createElement('div');c.className='current';c.textContent='CONFIGURATA';left.appendChild(c)}left.appendChild(name);left.appendChild(meta);right.className='sig';right.textContent=bars(n.rssi)+'  '+n.rssi+' dBm';row.appendChild(left);row.appendChild(right);row.onclick=()=>selectNet(n,row);box.appendChild(row)})}
async function startScan(){const b=q('scan');b.disabled=true;q('status').textContent='Avvio scansione Wi-Fi...';q('nets').textContent='';try{let r=await fetch('/api/wifi/scan',{method:'POST'});if(!r.ok&&r.status!==202)throw new Error(await r.text());for(let i=0;i<35;i++){await wait(450);r=await fetch('/api/wifi/scan');if(!r.ok)throw new Error(await r.text());const d=await r.json();if(d.status==='complete'){render(d.networks||[]);b.disabled=false;return}q('status').textContent='Scansione in corso...'}throw new Error('Timeout scansione Wi-Fi')}catch(e){q('status').textContent='Errore: '+e.message;b.disabled=false}}
async function saveWifi(){const ssid=q('ssid').value.trim(),pass=q('pass').value;if(!ssid){show('Selezionare una rete Wi-Fi.',false);return}const b=q('save');b.disabled=true;show('Salvataggio configurazione...',true);try{const body='ssid='+encodeURIComponent(ssid)+'&password='+encodeURIComponent(pass);const r=await fetch('/api/wifi/configure',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const t=await r.text();if(!r.ok)throw new Error(t);show('Configurazione salvata. ESP32 in riavvio; collegarsi ora alla rete '+ssid+'.',true)}catch(e){show('Errore: '+e.message,false);b.disabled=false}}
function show(t,ok){const m=q('msg');m.textContent=t;m.className='msg '+(ok?'ok':'bad')}
setTimeout(startScan,500);
</script></body></html>)HTML";

}  // namespace WifiSetupPage
